apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-camden
  namespace: camden
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi