apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
  name: pages
  namespace: camden
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
    spec:
      containers:
        - image: groverpriyanka/pages:1.0
          name: pages
          ports:
            - containerPort: 8080